# Generated by Django 5.0 on 2024-02-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
